name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          architecture: x64
          distribution: 'temurin'
      - name: Java Compiler Version 
        run: javac -version
      - name: Java Runner Version check
        run: java -version
      - name: Maven version check
        run: mvn --version
      - name: Maven Build
        run: mvn clean compile test install package

      

